import {
  ArrowDown2,
  ArrowLeft2,
  ArrowRight2,
  Book1,
  Calendar,
  ChartSquare,
  Clock,
  CloseCircle,
  Code1,
  Cpu,
  Danger,
  Data,
  DocumentCode,
  DocumentDownload,
  DocumentText,
  Export,
  Eye,
  EyeSlash,
  Flash,
  Folder2,
  Global,
  Hierarchy,
  Import,
  InfoCircle,
  Lock,
  Logout,
  MagicStar,
  Refresh,
  ScanBarcode,
  SearchNormal1,
  ShieldTick,
  Sms,
  TickCircle,
  Trash,
  User,
  Warning2,
} from 'iconsax-react'

export const Icons = {
  repos: Folder2,
  scan: ScanBarcode,
  report: DocumentText,
  history: Clock,
  account: User,

  secrets_detection: ShieldTick,
  gitignore_check: Folder2,
  quality_check: ChartSquare,
  readme_check: Book1,

  clean: TickCircle,
  issues_found: Warning2,
  partial: InfoCircle,
  unavailable: EyeSlash,
  error: CloseCircle,
  critical: Danger,

  scanned: ScanBarcode,
  completed: TickCircle,
  scanning: Refresh,
  analyzing: Refresh,
  processing: Refresh,
  pending: Clock,
  failed: CloseCircle,

  fetching: Import,
  indexing: Data,
  aiAnalyzing: Cpu,
  done: TickCircle,

  triage: MagicStar,
  running: Refresh,
  retry: Refresh,
  view: Eye,
  search: SearchNormal1,
  trash: Trash,
  logout: Logout,
  exportPdf: DocumentDownload,
  exportJson: DocumentCode,
  download: Export,

  commit: Hierarchy,
  code: Code1,
  test: Flash,
  quota: Flash,
  mail: Sms,
  calendar: Calendar,
  language: Global,
  private: Lock,
  public: Global,
  hidden: EyeSlash,

  back: ArrowLeft2,
  forward: ArrowRight2,
  expand: ArrowDown2,
  collapse: ArrowRight2,
}

export const ICON_DEFAULTS = {
  size: 18,
  variant: 'Linear',
}
